const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  // Auth
  login: (username, password) => ipcRenderer.invoke('auth:login', username, password),
  logout: () => ipcRenderer.invoke('auth:logout'),
  getCurrentUser: () => ipcRenderer.invoke('auth:getCurrentUser'),
  changePassword: (userId, currentPw, newPw) => ipcRenderer.invoke('auth:changePassword', userId, currentPw, newPw),
  switchSchool: (schoolId) => ipcRenderer.invoke('auth:switchSchool', schoolId),

  // Schools
  getSchools: () => ipcRenderer.invoke('schools:getAll'),
  getSchool: (id) => ipcRenderer.invoke('schools:get', id),
  addSchool: (data) => ipcRenderer.invoke('schools:add', data),
  updateSchool: (id, data) => ipcRenderer.invoke('schools:update', id, data),
  deleteSchool: (id) => ipcRenderer.invoke('schools:delete', id),

  // Users
  getUsers: (schoolId) => ipcRenderer.invoke('users:getAll', schoolId),
  addUser: (data) => ipcRenderer.invoke('users:add', data),
  updateUser: (id, data) => ipcRenderer.invoke('users:update', id, data),
  deleteUser: (id) => ipcRenderer.invoke('users:delete', id),

  // Dashboard
  getGlobalDashboard: () => ipcRenderer.invoke('db:getGlobalDashboard'),

  // Existing
  addStudent: (data) => ipcRenderer.invoke('db:addStudent', data),
  updateStudent: (id, data) => ipcRenderer.invoke('db:updateStudent', id, data),
  deleteStudent: (id) => ipcRenderer.invoke('db:deleteStudent', id),
  deleteMultipleStudents: (ids) => ipcRenderer.invoke('db:deleteMultipleStudents', ids),
  getStudents: (query) => ipcRenderer.invoke('db:getStudents', query),
  getStudent: (id) => ipcRenderer.invoke('db:getStudent', id),
  addSubject: (data) => ipcRenderer.invoke('db:addSubject', data),
  updateSubject: (id, data) => ipcRenderer.invoke('db:updateSubject', id, data),
  deleteSubject: (id) => ipcRenderer.invoke('db:deleteSubject', id),
  deleteMultipleSubjects: (ids) => ipcRenderer.invoke('db:deleteMultipleSubjects', ids),
  getSubjects: (query) => ipcRenderer.invoke('db:getSubjects', query),
  getSubject: (id) => ipcRenderer.invoke('db:getSubject', id),
  addTeacher: (data) => ipcRenderer.invoke('db:addTeacher', data),
  updateTeacher: (id, data) => ipcRenderer.invoke('db:updateTeacher', id, data),
  deleteTeacher: (id) => ipcRenderer.invoke('db:deleteTeacher', id),
  deleteMultipleTeachers: (ids) => ipcRenderer.invoke('db:deleteMultipleTeachers', ids),
  getTeachers: (query) => ipcRenderer.invoke('db:getTeachers', query),
  getTeacher: (id) => ipcRenderer.invoke('db:getTeacher', id),
  addStaff: (data) => ipcRenderer.invoke('db:addStaff', data),
  updateStaff: (id, data) => ipcRenderer.invoke('db:updateStaff', id, data),
  deleteStaff: (id) => ipcRenderer.invoke('db:deleteStaff', id),
  deleteMultipleStaff: (ids) => ipcRenderer.invoke('db:deleteMultipleStaff', ids),
  getStaffList: (query) => ipcRenderer.invoke('db:getStaffList', query),
  getStaff: (id) => ipcRenderer.invoke('db:getStaff', id),
  saveAttendance: (data) => ipcRenderer.invoke('db:saveAttendance', data),
  getAttendance: (query) => ipcRenderer.invoke('db:getAttendance', query),
  getAttendanceStats: (studentId, session) => ipcRenderer.invoke('db:getAttendanceStats', studentId, session),
  getSections: (query) => ipcRenderer.invoke('db:getSections', query),
  addSection: (data) => ipcRenderer.invoke('db:addSection', data),
  updateSection: (id, data) => ipcRenderer.invoke('db:updateSection', id, data),
  deleteSection: (id) => ipcRenderer.invoke('db:deleteSection', id),
  getRoutines: (query) => ipcRenderer.invoke('db:getRoutines', query),
  saveRoutines: (data) => ipcRenderer.invoke('db:saveRoutines', data),
  getFeeItems: (query) => ipcRenderer.invoke('db:getFeeItems', query),
  addFeeItem: (data) => ipcRenderer.invoke('db:addFeeItem', data),
  updateFeeItem: (id, data) => ipcRenderer.invoke('db:updateFeeItem', id, data),
  deleteFeeItem: (id) => ipcRenderer.invoke('db:deleteFeeItem', id),
  getFeeCollections: (query) => ipcRenderer.invoke('db:getFeeCollections', query),
  saveFeeCollection: (data) => ipcRenderer.invoke('db:saveFeeCollection', data),
  getFeeCollectionItems: (id) => ipcRenderer.invoke('db:getFeeCollectionItems', id),
  deleteFeeCollection: (id) => ipcRenderer.invoke('db:deleteFeeCollection', id),
  saveSubjectRegistrations: (data) => ipcRenderer.invoke('db:saveSubjectRegistrations', data),
  bulkSubjectRegistration: (data) => ipcRenderer.invoke('db:bulkSubjectRegistration', data),
  getSubjectRegistrations: (student_id, session) => ipcRenderer.invoke('db:getSubjectRegistrations', student_id, session),
  saveMarks: (data) => ipcRenderer.invoke('db:saveMarks', data),
  getMarks: (query) => ipcRenderer.invoke('db:getMarks', query),
  processResult: (data) => ipcRenderer.invoke('db:processResult', data),
  getResults: (query) => ipcRenderer.invoke('db:getResults', query),
  exportJSON: (type) => ipcRenderer.invoke('db:exportJSON', type),
  importJSON: (data) => ipcRenderer.invoke('db:importJSON', data),
  getSetting: (key) => ipcRenderer.invoke('db:getSetting', key),
  getAllSettings: () => ipcRenderer.invoke('db:getAllSettings'),
  setSetting: (key, value) => ipcRenderer.invoke('db:setSetting', key, value),
  getBooks: (query) => ipcRenderer.invoke('db:getBooks', query),
  getBook: (id) => ipcRenderer.invoke('db:getBook', id),
  saveBook: (data) => ipcRenderer.invoke('db:saveBook', data),
  deleteBook: (id) => ipcRenderer.invoke('db:deleteBook', id),
  getBookIssues: (query) => ipcRenderer.invoke('db:getBookIssues', query),
  issueBook: (data) => ipcRenderer.invoke('db:issueBook', data),
  returnBook: (id, date) => ipcRenderer.invoke('db:returnBook', id, date),
  backup: () => ipcRenderer.invoke('db:backup'),

  // Google Drive Backup
  driveConnect: () => ipcRenderer.invoke('drive:connect'),
  driveDisconnect: () => ipcRenderer.invoke('drive:disconnect'),
  driveBackupNow: () => ipcRenderer.invoke('drive:backupNow'),
  driveGetStatus: () => ipcRenderer.invoke('drive:getStatus'),
  driveSetSettings: (opts) => ipcRenderer.invoke('drive:setSettings', opts),
  driveRestoreFull: (fileId) => ipcRenderer.invoke('drive:restoreFull', fileId),
  driveRestoreSchool: (fileId, schoolId) => ipcRenderer.invoke('drive:restoreSchool', fileId, schoolId),
  driveDeleteFile: (fileId) => ipcRenderer.invoke('drive:deleteFile', fileId),
  driveDownloadFile: (fileId, savePath) => ipcRenderer.invoke('drive:downloadFile', fileId, savePath),
  driveApplyFullRestore: () => ipcRenderer.invoke('drive:applyFullRestore'),
  openExternal: (url) => ipcRenderer.invoke('util:openExternal', url),
  saveFile: (opts) => ipcRenderer.invoke('dialog:saveFile', opts),
  openFile: (opts) => ipcRenderer.invoke('dialog:openFile', opts),
  saveLogo: (base64) => ipcRenderer.invoke('db:saveLogo', base64),
  bsToAd: (bsDate) => ipcRenderer.invoke('nepali:bsToAd', bsDate),
});
